package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DeployLocalTeamCityPackage'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DeployLocalTeamCityPackage")) {
    dependencies {
        expect(RelativeId("BuildAndTest")) {
            artifacts {
                buildRule = lastSuccessful("""
                    +:<default>
                    +:*
                """.trimIndent())
                cleanDestination = true
                artifactRules = "+:NoeticTools.Git2SemVer.Framework.*.nupkg"
            }
        }
        update(RelativeId("BuildAndTest")) {
            artifacts {
                buildRule = lastSuccessful("""
                    +:<default>
                    +:*
                """.trimIndent())
                cleanDestination = true
                artifactRules = "+:NoeticTools.Git2SemVer.Framework.*.nupkg"
            }
        }

    }
}
